### Site Settings ###
title               : Çağrı Himmetoğlu
description         : >-
                      Turning coffee :coffee: and tea :tea: into code and enjoying it.
# baseurl             : "/portfolYOU"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : YoussefRaafatNasry/portfolYOU     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : false                             # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
#  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : Çağrı Himmetoğlu
  image             : https://i.ibb.co/ZzgzycS/pfp.jpg
# behance           : your_username
# dribbble          : your_username
  email             : cagrihimmetoglu@gmail.com
#  facebook          : your_username
  github            : kegri
# gitlab            : your_username
  instagram         : shimijda
# kaggle            : your_username
  linkedin          : çağrı-himmetoğlu-961a96253
# medium            : your_username
# soundcloud        : your_username
  spotify           : ndco0dw6ffhwltl440pjw32gs
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
  twitch            : mitnarachnun
  twitter           : kegrine
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only


### Disqus ###
disqus:
  shortname: cagrihimmetoglu-com-tr                 # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: 360887724


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: true
  username: kegrine
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
